# Generated by Django 2.2.1 on 2020-07-23 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot_booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='washingmechine',
            old_name='image',
            new_name='washing_machine_image',
        ),
    ]
