# Generated by Django 2.2.1 on 2020-07-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot_booking', '0002_issues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='reported_dat_time',
            new_name='reported_date_time',
        ),
    ]
