# Generated by Django 2.2.1 on 2020-08-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot_booking', '0003_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.IntegerField()),
            ],
        ),
    ]
